name: TableSpoon
main: Xenophilicy\TableSpoon\TableSpoon
version: 0.0.6-ALPHA
api: 3.13.0
authors: [ CortexPE, Xenophilicy, HyperFlareMC ]
description: Adds cool features to PocketMine
load: STARTUP